#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QA_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT="$(cd "$QA_ROOT/../.." && pwd)"
MODE="--quick"
AGENT_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --quick|--full)
      MODE="$1"
      shift
      ;;
    --agent)
      AGENT_ID="${2:-}"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

REPORT_DIR="${QA_REPORT_DIR:-$QA_ROOT/reports}"
mkdir -p "$REPORT_DIR"
REPORT_PATH="$REPORT_DIR/qa-report-$(date +%Y%m%d-%H%M%S).md"

VALIDATOR_OUTPUT="$(mktemp)"
trap 'rm -f "$VALIDATOR_OUTPUT"' EXIT

if [[ "$MODE" == "--full" ]]; then
  bash "$ROOT/scripts/validate-autonomous-setup.sh" >"$VALIDATOR_OUTPUT"
else
  bash "$ROOT/scripts/validate-autonomous-setup.sh" --check-only >"$VALIDATOR_OUTPUT"
fi

{
  echo "# QA Report"
  echo
  echo "- Mode: $MODE"
  if [[ -n "$AGENT_ID" ]]; then
    echo "- Agent: $AGENT_ID"
  else
    echo "- Agent: (not specified)"
  fi
  echo "- Generated by: ${QA_GENERATED_BY:-OpenClaw QA Framework}"
  echo "- Validator: scripts/validate-autonomous-setup.sh"
  echo
  echo "## Validator Output"
  echo
  cat "$VALIDATOR_OUTPUT"
  echo
  echo "## Runtime Notes"
  echo
  if command -v openclaw >/dev/null 2>&1; then
    echo "- openclaw CLI detected"
    if [[ "$MODE" == "--full" ]]; then
      echo "- openclaw version: $(openclaw --version 2>/dev/null || echo unavailable)"
    else
      echo "- runtime checks skipped in quick mode"
    fi
  else
    echo "- openclaw CLI not detected in current environment"
  fi
} >"$REPORT_PATH"

echo "QA ${MODE#--} checks passed"
echo "Report: $REPORT_PATH"
